version: '3.13.9'


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dockerbase
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 8010:8010

  web:
    build: .
    command: python /stego/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/stego
    ports: 
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: